<<<<<<< HEAD
name: tf2
=======
name: tf1
>>>>>>> upstream/master
channels:
  - conda-forge
  - defaults
dependencies:
  - graphviz
<<<<<<< HEAD
  - imageio=2.6.1
  - ipython=7.10.1
  - ipywidgets=7.5.1
  - joblib=0.14.0
  - jupyter=1.0.0
  - matplotlib=3.1.2
  - nbdime=1.1.0
  - nltk=3.4.5
  - numexpr=2.7.0
  - numpy=1.17.3
  - pandas=0.25.3
  - pillow=6.2.1
  - pip
  - py-xgboost=0.90
  - pydot=1.4.1
  - pyopengl=3.1.3b2
  - python=3.7
  - python-graphviz
  - requests=2.22.0
  - scikit-image=0.16.2
  - scikit-learn=0.22
  - scipy=1.3.1
  - tqdm=4.40.0
  - tensorboard=2.0.0
  - tensorflow=2.0.0 # or tensorflow-gpu if gpu
  - tensorflow-datasets=1.2.0
  - tensorflow-estimator=2.0.0
  - tensorflow-hub=0.7.0
  - tensorflow-probability=0.7
  - wheel
  - widgetsnbextension=3.5.1
  - pip:
    - atari-py==0.2.6
    - gym==0.15.4
    - opencv-python==4.1.2.30
    - psutil==5.6.7
    - pyglet==1.3.2
    - tensorflow-addons==0.6.0
    - tensorflow-data-validation==0.15.0
    - tensorflow-metadata==0.15.1
    - tensorflow-model-analysis==0.15.4
    - tensorflow-serving-api==2.0.0 # or tensorflow-serving-api-gpu if gpu
    - tensorflow-transform==0.15.0
    - tf-agents==0.3.0rc0
    - tfx==0.15.0
    - urlextract==0.13.0
    #- pyvirtualdisplay # add if on headless server
=======
  - imageio=2.6
  - ipython=7.12
  - ipywidgets=7.5
  - joblib=0.14
  - jupyter=1.0
  - matplotlib=3.1
  - nbdime=2.0
  - nltk=3.4
  - numexpr=2.7
  - numpy=1.18
  - pandas=1.0
  - pillow=7.0
  - pip
  - psutil=5.7
  - py-xgboost=0.90
  - pydot=1.4
  - pyglet=1.5
  - pyopengl=3.1
  - python=3.7
  - python-graphviz
  #- pyvirtualdisplay=0.2 # add if on headless server
  - requests=2.22
  - scikit-image=0.16
  - scikit-learn=0.22
  - scipy=1.4
  - tensorflow-base=1.15
  - tensorflow=1.15 # or tensorflow-gpu if you have a GPU
  - tensorboard=1.15
  - tensorflow-estimator=1.15
  - tqdm=4.43
  - wheel
  - widgetsnbextension=3.5
  - pip:
    - atari-py==0.2.6
    - gast==0.2.2
    - gym==0.17.1
    - opencv-python==4.2.0.32
    - tensorflow-serving-api==1.15.0 # or tensorflow-serving-api-gpu if GPU
    - urlextract==0.14.0
>>>>>>> upstream/master
